/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert('parts', [
      {
        name: 'AMD Ryzen 5 5600X',
        type: 'cpu',
        manufacturer: 'AMD',
        releaseDate: '2020-11-03',
        price: 158.97,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Intel Core i7-12700K',
        type: 'cpu',
        manufacturer: 'Intel',
        releaseDate: '2021-10-18',
        price: 357.95,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'AMD Ryzen 7 5800X',
        type: 'cpu',
        manufacturer: 'AMD',
        releaseDate: '2022-03-25',
        price: 248.0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Corsair Vengeance LPX 16 GB',
        type: 'ram',
        manufacturer: 'Corsair',
        releaseDate: '2021-06-07',
        price: 54.99,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Corsair Vengeance RGB Pro 32 GB',
        type: 'ram',
        manufacturer: 'Corsair',
        releaseDate: '2022-01-16',
        price: 114.99,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MSI MAG B550 TOMAHAWK ATX AM4 Motherboard',
        type: 'motherboard',
        manufacturer: 'MSI',
        releaseDate: '2020-06-29',
        price: 169.99,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MSI MAG B660 TOMAHAWK WIFI DDR4 ATX LGA1700 Motherboard',
        type: 'motherboard',
        manufacturer: 'MSI',
        releaseDate: '2022-01-04',
        price: 169.99,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Samsung 970 Evo Plus 1 TB M.2-2280 PCIe 3.0 X4 NVME Solid State Drive',
        type: 'memory',
        manufacturer: 'Samsung',
        releaseDate: '2022-01-04',
        price: 89.99,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Samsung 980 Pro 2 TB M.2-2280 PCIe 4.0 X4 NVME Solid State Drive',
        type: 'memory',
        manufacturer: 'Samsung',
        releaseDate: '2022-01-04',
        price: 199.99,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'MSI GeForce RTX 3060 Ventus 2X 12G GeForce RTX 3060 12GB 12 GB Video Card',
        type: 'gpu',
        manufacturer: 'MSI',
        releaseDate: '2022-01-04',
        price: 369.99,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'G.Skill Trident Z5 RGB 32 GB (2 x 16 GB) DDR5-8000 CL38 Memory',
        type: 'ram',
        manufacturer: 'G.Skill',
        releaseDate: '2022-01-16',
        price: 529.99,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'PNY VCGGT7102XPB GeForce GT 710 2 GB PCIe x8 Video Card',
        type: 'gpu',
        manufacturer: 'PNY',
        releaseDate: '2022-01-16',
        price: 54.99,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Kingston KC600 1.024 TB mSATA Solid State Drive',
        type: 'memory',
        manufacturer: 'Kingston',
        releaseDate: '2022-01-16',
        price: 128.97,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('parts', null, {});
  },
};
